![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**

#**10.25. Modul boʻyicha yakuniy amaliy vazifa**

**Amaliyotni bajargach, fayllar bilan ishlash, API va veb sahifalardan ma’lumot olish, SQL soʻrovlarini yozish va ma’lumotlar omboriga ma’lumot saqlash koʻnikmalariga ega boʻlasiz.**

#**Fayldan oʻqish va yozish**

In [1]:
import pandas as pd
import sqlite3 as sql
import requests
from io import StringIO
from IPython.display import display

#**1) CSV fayldan maʼlumotlarni o‘qish**
* https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv havolasidagi maʼlumotlarni `df` oʻzgaruvchisiga saqlang!
* `df` dan tasodifiy 10 ta qatorni ekranga chiqaring!

In [2]:
#javobni shu yerda yozing.
df = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
pd.read_csv(df).sample(10)

             Date     Country                          Status  AQI Value
1534   2022-07-26      Sweden                            Good         18
724    2022-07-23      Brazil  Unhealthy for Sensitive Groups        129
3752   2022-08-11  Madagascar                            Good         23
8591   2022-09-14      Angola                        Moderate         77
4672   2022-08-18      Brazil                        Moderate         88
5148   2022-08-21  Kazakhstan                        Moderate         84
4555   2022-08-17     Finland                        Moderate         54
4683   2022-08-18       China                       Unhealthy        161
2119   2022-07-31     Andorra                            Good         23
16918  2025-01-02       China                  Very Unhealthy        232

#**2) CSV fayliga yozish**
* Quyidagi maʼlumotlardan dataframe yarating va uni `people_data.csv` fayliga saqlang.
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```
* Quyidagi maʼlumotlardan yana bir dataframe yarating va uni `people_data_2.csv` fayliga saqlang.
```
{
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
```

In [3]:
# 2.0 Dictionary ma'lumotlarni DataFrame ga o'girib people_data.csv fayliga yozish
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}

df = pd.DataFrame(data)
df.to_csv("people_data.csv", index=False)

In [4]:
# 2.1 Dictionary ma'lumotlarni DataFrame ga o'girib people_data2.csv fayliga yozish
data2 = {
'Name': ['Alice', 'Bob', 'Charlie'],
'Age': [25, 30, 35]
}
df2 = pd.DataFrame (data2)
df2.to_csv("people_data2.csv", index=False)

#**3) HDF5 formati bilan ishlash**
* Yuqorida yaratgan dataframeʼlaringizni `people.h5` faylida saqlang.
* `people.h5` faylidagi barcha jadvallarni oʻqing!

In [5]:
# 3.0 HDF5 faylini yaratish
hdfobj = pd.HDFStore("people.h5")

In [6]:
# 3.1 people_data nomli key yaratish
hdfobj.put('people_data', df)

In [7]:
# 3.1 people_data2 nomli key yaratish
hdfobj.put('people_data2', df2)

In [8]:
# 3.2 keys larni tekshirish
hdfobj.keys()

['/people_data', '/people_data2']

In [9]:
# 3.3 ma'lumotlarni o'qish
hdfobj['people_data']

      Name  Age       City
0    Alice   25   Tashkent
1      Bob   30  Samarkand
2  Charlie   35    Bukhara
3    David   40    Andijan
4      Eve   28      Nukus
5    Frank   33      Khiva
6    Grace   38   Namangan
7   Hannah   45    Fergana
8      Ivy   29    Jizzakh
9     Jack   31     Termez

In [10]:
# 3.3 ma'lumotlarni o'qish
hdfobj['people_data2']

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

#**4) JSON fayllar bilan ishlash**
1. Quyidagi maʼlumotlarni dataframe koʻrinishida oʻqing va uni `data.json` fayliga yozing!
```
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
```

In [11]:
# 4.0 JSON fayliga yozish
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah", "Ivy", "Jack"],
    "Age": [25, 30, 35, 40, 28, 33, 38, 45, 29, 31],
    "City": ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Nukus", "Khiva", "Namangan", "Fergana", "Jizzakh", "Termez"]
}
df4 = pd.DataFrame(data)
df4.to_json('data.json')

#**5) APIʼlar bilan ishlash**
1. Quyida berilgan API 17 mingdan ortiq kriptovalyutalarning dollarga nisbatan narxi haqidagi maʼlumotlarni saqlaydi. Siz esa endi:
  * API orqali barcha maʼlumotlarni yigʻib oling;
  * ularni dataframe koʻrinishida saqlang;
  * maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring;
  * maʼlumotlar ichidan `bitcoin` ni izlab toping!

In [12]:
#API'lardan ma'lumotlar olish
coins_url = "https://api.coingecko.com/api/v3/coins/list" # API dan kelgan ma'lumotlarni o'zgaruvchiga saqlash
coins = pd.read_json(coins_url) # API orqali kelgan ma'lumotni o'qish
coin_df = pd.DataFrame(coins) # dataframe koʻrinishida saqlash
coin_df.head(5) # ma'lumotlar boshidan 5 ta qatorni ekranga chiqarish

,id,symbol,name
0,_,gib,༼ つ ◕_◕ ༽つ
1,000-capital,000,000 Capital
2,01111010011110000110001001110100-token,01111010011110000110001001110100,01111010011110000110001001110100
3,01112131415161718192021222324252-token,1234567891,01112131415161718192021222324252
4,01-token,01,01

In [120]:
# 5 ma'lumotlar ichidan bitcoin ni izlab topish
bitcoin = coin_df["name"].str.lower().str.strip() == "bitcoin"
pd.DataFrame((coin_df[bitcoin]))

           id symbol     name
2701  bitcoin    btc  Bitcoin

#**6) APIʼlar bilan ishlash**
1. Yuqorida berilgan kriptovalyuta maʼlumotlaridan `id` ustunini roʻyxat koʻrinishida saqlang va bu roʻyxatga `coin_ids` deb nom bering.
2. https://api.coingecko.com/api/v3/simple/price?ids={coin_ids}&vs_currencies=usd havolasi orqali kriptovalyutalarning `usd` ga nisbatini oling (birinchi 100 ta maʼlumotni olish yetarli).
3. 2-shartda berilgan link orqali olingan maʼlumotlarni dataframe koʻrinishida saqlang. Bunda uning indeksi va `usd` ustuni boʻlsin. `index` -> kriptovalyutalar nomi, `usd` -> narxi

#**💡Ishora:** linkdagi `{coin_ids}` oʻzgaruvchi sifatida yozilgan. Siz ham 1-shartda saqlagan `coin_ids` oʻzgaruvchingizni shu qismda yozib keting!

In [119]:
# 6.1  id ustunini ro'yxat qilib saqlash
coin_ids = coins["id"].tolist()[:100]   # birinchi 100 ta

# 6.2 linkka qo'yish (ro'yxatni matnga aylantirib)
ids_str = ",".join(coin_ids)
url = f"https://api.coingecko.com/api/v3/simple/price?ids={ids_str}&vs_currencies=usd"
data = requests.get(url).json()

# 6.3 index -> coin nomi, ustun -> usd
prices = pd.DataFrame.from_dict(data, orient="index")
prices

                                             usd
_                                       0.001826
000-capital                             0.000012
01111010011110000110001001110100-token  0.000013
01112131415161718192021222324252-token  0.000004
01-token                                0.000037
...                                          ...
4                                       0.000005
401jk                                   0.000929
401k                                    0.000015
404-gen                                 1.970000
4-2                                     0.012942

[94 rows x 1 columns]

#**7) Veb sahifadan oʻqish**
1. Pandas yordamida veb sahifadagi jadvalni yuklab oling.
2. Ma’lumotlarni dataframe ko‘rinishida chiqaring.
3. Agar sahifada bir nechta jadval bo‘lsa, eng muhimini tanlang.
4. Ma’lumotni tozalang (bo‘sh qatorlarni olib tashlang, kerakli ustunlarni tanlang).
5. Natijani CSV faylga saqlang.

***Eslatma: manba sifatida oʻzingiz istagan veb sahifani tanlang. Bu vazifada mustaqil izlanishni oʻrganasiz!***

In [121]:
# 7.1 Pandas yordamida veb sahifadagi jadvalni yuklab olish
url = "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
table = pd.read_html(StringIO(response.text))
df = pd.DataFrame(table[2])
df.head(15)

,Country/Territory,IMF (2026)[1],World Bank (2025)[6],United Nations (2024)[7]
0,World,128003776,118350166,111565144
1,United States,32642373,30769700,29298000
2,China[n 1],21546403,19498039,18743802
3,Germany,5471299,5050923,4659929
4,Japan,4341986,4435163,4026211
5,United Kingdom,4268446,4002588,3685881
6,India,4060207,3956067,3952244
7,France,3554155,3366316,3160443
8,Russia,2861156,2561310,2173386
9,Italy,2701737,2551557,2380825
10,Brazil,2654761,2279920,2185822
11,Canada,2490256,2319900,2270076
12,South Korea,2245847,1872375,1875388
13,Mexico,2176236,1832641,1852723
14,Australia,2110657,1798519,1830610

In [40]:
# 7.2 ustun nomlarini o'zgartirish
df.rename(columns={"Country/Territory": "Country", "IMF (2026)[1]": "IMF_2026", "World Bank (2025)[6]": "WorldBank_2026", "United Nations (2024)[7]": "UNO_2025"}, inplace=True)
df

              Country   IMF_2026 WorldBank_2026   UNO_2025
0               World  128003776      118350166  111565144
1       United States   32642373       30769700   29298000
2          China[n 1]   21546403       19498039   18743802
3             Germany    5471299        5050923    4659929
4               Japan    4341986        4435163    4026211
..                ...        ...            ...        ...
217             Palau        377            345        310
218  Marshall Islands        342            308        281
219             Nauru        196            176        187
220        Montserrat       —N/a           —N/a         81
221            Tuvalu         65             57         56

[222 rows x 4 columns]

In [18]:
# 7.3 Ma'lumotlarni tozalash
cols = ["IMF_2026", "WorldBank_2026", "UNO_2025"]
# 1. Har bir ustunni songa aylantirish (son bo'lmaganlar NaN bo'ladi)
numeric = df[cols].apply(pd.to_numeric, errors="coerce")
# 2. Uch ustunda ham son bor qatorlar uchun niqob (mask)
mask = numeric.notna().all(axis=1)
# 3. Faqat shu qatorlarni qoldirish
df_clean = df[mask].copy()
# 4. Ustunlarni haqiqiy son turiga o'tkazish
df_clean[cols] = numeric[mask]
# Tekshirish
df_clean

              Country     IMF_2026  WorldBank_2026     UNO_2025
0               World  128003776.0     118350166.0  111565144.0
1       United States   32642373.0      30769700.0   29298000.0
2          China[n 1]   21546403.0      19498039.0   18743802.0
3             Germany    5471299.0       5050923.0    4659929.0
4               Japan    4341986.0       4435163.0    4026211.0
..                ...          ...             ...          ...
216          Kiribati        401.0           349.0        343.0
217             Palau        377.0           345.0        310.0
218  Marshall Islands        342.0           308.0        281.0
219             Nauru        196.0           176.0        187.0
221            Tuvalu         65.0            57.0         56.0

[184 rows x 4 columns]

In [19]:
# 7.4 Ma'lumotlarni CSV faylga yozish
df_clean.to_csv("gdp.csv")

# **Maʼlumotlar ombori bilan ishlash**

#**8) Maʼlumotlar omborini yuklash va ulanish**
1. https://github.com/alishermutalov/praktikum-datasets/blob/praktikum/chinook.db havolasi orqali maʼlumotlar omborini yuklab oling.
2. Yuklab olingan maʼlumotlar omboriga sqlite3 moduli yordamida **ulaning**.

In [20]:
!wget https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
!unzip "chinook.zip"

--2026-10-20 09:24:51--  https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
Resolving www.sqlitetutorial.net (www.sqlitetutorial.net)... 104.21.30.141, 172.67.172.250, 2606:4700:3031::6815:1e8d, ...
Connecting to www.sqlitetutorial.net (www.sqlitetutorial.net)|104.21.30.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 305596 (298K) [application/zip]
Saving to: ‘chinook.zip’

chinook.zip         100%[===================>] 298.43K  --.-KB/s    in 0.03s

2026-10-20 09:24:52 (9.44 MB/s) - ‘chinook.zip’ saved [305596/305596]

Archive:  chinook.zip
  inflating: chinook.db

In [21]:
# 8.1 DB ga ulanish
db = sql.connect('chinook.db')
cursor = db.cursor()

#**9) Maʼlumotlar omboriga soʻrov yuborish**
1. Jadvallar roʻyxatini koʻring. Ularning ichida `albums` jadvali boʻlsa, shu jadvaldagi barcha maʼlumotlarni (qatorlarni) ekranga chiqaring.
2. Qatorlar soni nechta ekanini aniqlab, uni ham ekranga chiqaring.
3.`albums` jadvalining ustunlari haqidagi maʼlumotlarni ekranga chiqaring.

In [22]:
# 9.1 jadvallar ro'yxatini ko'rish
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('albums',), ('sqlite_sequence',), ('artists',), ('customers',), ('employees',), ('genres',), ('invoices',), ('invoice_items',), ('media_types',), ('playlists',), ('playlist_track',), ('tracks',), ('sqlite_stat1',)]

In [23]:
# 9.2 albums jadvalidagi qatorlarni ko'rish
cursor.execute("SELECT COUNT (*) FROM albums")
cursor.fetchone()

(347,)

In [41]:
# 9.3 albums jadvali ustunlarini ko'ramiz
cursor.execute("PRAGMA table_info(albums);")
cursor.fetchall()

[(0, 'AlbumId', 'INTEGER', 1, None, 1),
 (1, 'Title', 'NVARCHAR(160)', 1, None, 0),
 (2, 'ArtistId', 'INTEGER', 1, None, 0)]

#**10) SQL to DataFrame**
1. `albums` jadvalini `pandas.DataFrame` ga oʻtkazing!

In [25]:
# 10.1 albums jadvalini DF ga yuklash
df_albums = pd.read_sql_query("SELECT * FROM albums;", db)
df_albums

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
..       ...                                                ...       ...
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

#**11)**  `chinook.db` maʼlumotlar omboridan `tracks` jadvalining birinchi 10 ta qatorini ekranga chiqaring

#💡Ishora: LIMIT

In [26]:
# 11 track jadvalini print qilish
tracks = pd.read_sql_query("SELECT * FROM tracks LIMIT 10;", db)
tracks

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,1,For Those About To Rock (We Salute You),1,1,1,"Angus Young, Malcolm Young, Brian Johnson",343719,11170334,0.99
1,2,Balls to the Wall,2,2,1,None,342562,5510424,0.99
2,3,Fast As a Shark,3,2,1,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",230619,3990994,0.99
3,4,Restless and Wild,3,2,1,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",252051,4331779,0.99
4,5,Princess of the Dawn,3,2,1,Deaffy & R.A. Smith-Diesel,375418,6290521,0.99
5,6,Put The Finger On You,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",205662,6713451,0.99
6,7,Let's Get It Up,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",233926,7636561,0.99
7,8,Inject The Venom,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",210834,6852860,0.99
8,9,Snowballed,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",203102,6599424,0.99
9,10,Evil Walks,1,1,1,"Angus Young, Malcolm Young, Brian Johnson",263497,8611245,0.99

#**12)**`tracks` jadvalidan faqat `Name`, `Composer` ustunlarini tanlab oling!

In [27]:
# 12 tracks jadvalidan faqat Name, Composer ustunlarini tanlab olish
tracks = pd.read_sql_query("SELECT Name, Composer FROM tracks LIMIT 10", db)
tracks

,Name,Composer
0,For Those About To Rock (We Salute You),"Angus Young, Malcolm Young, Brian Johnson"
1,Balls to the Wall,None
2,Fast As a Shark,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho..."
3,Restless and Wild,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D..."
4,Princess of the Dawn,Deaffy & R.A. Smith-Diesel
5,Put The Finger On You,"Angus Young, Malcolm Young, Brian Johnson"
6,Let's Get It Up,"Angus Young, Malcolm Young, Brian Johnson"
7,Inject The Venom,"Angus Young, Malcolm Young, Brian Johnson"
8,Snowballed,"Angus Young, Malcolm Young, Brian Johnson"
9,Evil Walks,"Angus Young, Malcolm Young, Brian Johnson"

#**13) ORDER BY , DISTINCT**
* `tracks` jadvalidagi takrorlanmaydigan `GenreId` qiymatlarini oling.
* `tracks` jadvalidagi treklarni `Milliseconds` ustuni bo‘yicha kamayish tartibida saralang.

#💡Ishora: ORDER BY , DISTINCT

In [28]:
# 13.1 GenreId ichidagi ma'lumotlarni DISTINCT orqali sort qilib ko'rish
genre_id = pd.read_sql_query("SELECT DISTINCT GenreId FROM tracks", db)
genre_id

    GenreId
0         1
1         2
2         3
3         4
4         5
5         6
6         7
7         8
8         9
9        10
10       11
11       12
12       13
13       14
14       15
15       16
16       17
17       18
18       19
19       20
20       21
21       22
22       23
23       24
24       25

In [42]:
# 13.2 ORDER BY orqali eng kichik qiymatdan boshlab sort qilish
track_time = pd.read_sql_query("SELECT * FROM tracks ORDER BY Milliseconds LIMIT 10", db)
track_time

,TrackId,Name,AlbumId,MediaTypeId,GenreId,Composer,Milliseconds,Bytes,UnitPrice
0,2461,É Uma Partida De Futebol,200,1,1,Samuel Rosa,1071,38747,0.99
1,168,Now Sports,18,1,4,None,4884,161266,0.99
2,170,A Statistic,18,1,4,None,6373,211997,0.99
3,178,Oprah,18,1,4,None,6635,224313,0.99
4,3304,Commercial 1,258,1,17,L. Muggerud,7941,319888,0.99
5,172,The Real Problem,18,1,4,None,11650,387360,0.99
6,3310,Commercial 2,258,1,17,L. Muggerud,21211,850698,0.99
7,2241,Bossa,184,1,17,None,29048,967098,0.99
8,1086,Casinha Feliz,85,1,10,Gilberto Gil,32287,1039615,0.99
9,246,Mateus Enter,24,1,7,Chico Science,33149,1103013,0.99

#**14) Filtering**
 * `invoices` jadvalidan `Total` summasi 10 dan katta bo‘lgan maʼlumotlarni tanlang.

# 💡Ishora: WHERE

In [43]:
# 14.1 10 dan katta bo‘lgan maʼlumotlarni tanlash
invoices = pd.read_sql_query("SELECT * FROM invoices WHERE Total >= 10 LIMIT 10", db)
invoices

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
1,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
2,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
3,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
4,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86
5,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
6,47,15,2009-07-16 00:00:00,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,13.86
7,54,53,2009-08-16 00:00:00,113 Lupus St,London,None,United Kingdom,SW1V 3EN,13.86
8,61,32,2009-09-16 00:00:00,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,13.86
9,68,11,2009-10-17 00:00:00,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,13.86

#**15) CREATE and INSERT**
* `chinook.db` maʼlumotlar omboriga `users` jadvali yarating. Foydalanuvchilarning har biri uchun berilgan yosh qiymatlaridan foydalanib, birth_date ustunini to‘ldirish strategiyasini ishlab chiqing va amalda qo‘llang. Jadval maydonlari (ustunlar):
  * `id`
  * `name`
  * `birth_date`
* Yaratilgan `users` jadvaliga quyidagi maʼlumotlarni qoʻshing:

    * ```
    [
    ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22),
    ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31),
    ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23),
    ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)
]
 ```

#💡Ishora: CREATE TABLE, INSERT

In [31]:
#javobni shu yerda yozing.
query = """
CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY,
name TEXT,
age INTEGER,
birth_date DATE
);
"""
cursor.execute(query)
db.commit()

[ ('Alice', 25), ('Bob', 30), ('Charlie', 35), ('David', 28), ('Eve', 22), ('Frank', 40), ('Grace', 27), ('Hannah', 32), ('Ivy', 29), ('Jack', 31), ('Kevin', 33), ('Liam', 26), ('Mia', 24), ('Noah', 36), ('Olivia', 23), ('Peter', 39), ('Quinn', 37), ('Rachel', 34), ('Samuel', 41), ('Tina', 21)

]

In [32]:
query = """
INSERT INTO users (name, age)
VALUES ('Alice', 25),
('Bob', 30),
('Charlie', 35),
('David', 28),
('Eve', 22),
('Frank', 40),
('Grace', 27),
('Hannah', 32),
('Ivy', 29),
('Jack', 31),
('Kevin', 33),
('Liam', 26),
('Mia', 24),
('Noah', 36),
('Olivia', 23),
('Peter', 39),
('Quinn', 37),
('Rachel', 34),
('Samuel', 41),
('Tina', 21)
;
"""
cursor.execute(query)
db.commit()

In [33]:
users = pd.read_sql_query("SELECT id, name, age, CAST(strftime('%Y', 'now') AS INTEGER) - age AS birth_date FROM users LIMIT 10", db)
users.set_index("id")

       name  age  birth_date
id
1     Alice   25        2001
2       Bob   30        1996
3   Charlie   35        1991
4     David   28        1998
5       Eve   22        2004
6     Frank   40        1986
7     Grace   27        1999
8    Hannah   32        1994
9       Ivy   29        1997
10     Jack   31        1995

#**16) UPDATE and DELETE**
* `users` jadvalidagi Alice ismli foydalanuvchining yoshini yangilang.
* `users` jadvalidan Alice ismli foydalanuvchini o‘chiring.

In [34]:
# 16.1 UPDATE metodi orqali foydalanuvchini yoshini yangilash
query = """
UPDATE users SET age = 28 WHERE id = 1;
"""
cursor.execute(query)
db.commit()

In [45]:
# 16.2 DELETE metodi yordamida foydalanuvchini o'chirish
query = """
DELETE FROM users WHERE id = 1;
"""
cursor.execute(query)
db.commit()

In [46]:
users = pd.read_sql_query("SELECT id, name, age, CAST(strftime('%Y', 'now') AS INTEGER) - age AS birth_date FROM users LIMIT 10", db)
users.set_index("id")

       name  age  birth_date
id
2       Bob   30        1996
3   Charlie   35        1991
4     David   28        1998
5       Eve   22        2004
6     Frank   40        1986
7     Grace   27        1999
8    Hannah   32        1994
9       Ivy   29        1997
10     Jack   31        1995
11    Kevin   33        1993

`#**17) f-string yordamida SQL komandalarini yozish**
* `customers` jadvalidan `FirstName` va `LastName` bo‘yicha qidiruv qiladigan f-string yozing.

In [82]:
pd.read_sql_query("SELECT FirstName, LastName FROM customers", db)

    FirstName      LastName
0        Luís     Gonçalves
1      Leonie        Köhler
2    François      Tremblay
3       Bjørn        Hansen
4   František   Wichterlová
5      Helena          Holý
6      Astrid        Gruber
7        Daan       Peeters
8        Kara       Nielsen
9     Eduardo       Martins
10  Alexandre         Rocha
11    Roberto       Almeida
12   Fernanda         Ramos
13       Mark       Philips
14   Jennifer      Peterson
15      Frank        Harris
16       Jack         Smith
17   Michelle        Brooks
18        Tim         Goyer
19        Dan        Miller
20      Kathy         Chase
21    Heather       Leacock
22       John        Gordon
23      Frank       Ralston
24     Victor       Stevens
25    Richard    Cunningham
26    Patrick          Gray
27      Julia       Barnett
28     Robert         Brown
29     Edward       Francis
30     Martha          Silk
31      Aaron      Mitchell
32      Ellie      Sullivan
33       João     Fernandes
34   Madalena       Sampaio
35     Hannah     Schneider
36       Fynn    Zimmermann
37     Niklas      Schröder
38    Camille       Bernard
39  Dominique      Lefebvre
40       Marc        Dubois
41      Wyatt        Girard
42   Isabelle       Mercier
43      Terhi    Hämäläinen
44   Ladislav        Kovács
45       Hugh      O'Reilly
46      Lucas       Mancini
47   Johannes  Van der Berg
48  Stanisław        Wójcik
49    Enrique         Muñoz
50     Joakim     Johansson
51       Emma         Jones
52       Phil        Hughes
53      Steve        Murray
54       Mark        Taylor
55      Diego     Gutiérrez
56       Luis         Rojas
57      Manoj        Pareek
58       Puja    Srivastava

In [83]:
# 1. Qidiruv qiymatlari
first = "Dominique"
last = "Lefebvre"

# 2. SQL komandasini f-string bilan yozish
query = f"""
SELECT FirstName, LastName
FROM customers
WHERE FirstName = '{first}' AND LastName = '{last}'
"""

# 3. Ishga tushirish
result = pd.read_sql_query(query, db)
result

   FirstName  LastName
0  Dominique  Lefebvre

#**18)  AND and OR operators**

* `invoices` jadvalidan `BillingCountry` Germaniya yoki Fransiya boʻlgan va `Total` summasi 5 dan katta bo‘lgan kerakli qatorlarni tanlang.

#💡Ishora: AND, OR

In [89]:
# 18.1 AND and OR operatorlari
pd.read_sql_query("SELECT * FROM invoices WHERE (BillingCountry='Germany' OR BillingCountry='France') AND Total > 5", db)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
1,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
2,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
3,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
4,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
5,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
6,74,40,2009-11-12 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,8.91
7,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
8,117,41,2010-05-22 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,13.86
9,129,43,2010-07-15 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,5.94
10,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
11,150,39,2010-10-16 00:00:00,"4, Rue Milton",Paris,None,France,75009,5.94
12,172,41,2011-01-20 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,8.91
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,215,42,2011-07-30 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,13.86
15,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
16,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
17,248,40,2011-12-24 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,5.94
18,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
19,270,42,2012-03-29 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,8.91
20,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
21,313,43,2012-10-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,16.86
22,334,39,2013-01-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,13.86
23,346,41,2013-03-02 00:00:00,"11, Place Bellecour",Lyon,None,France,69002,5.94
24,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94
25,368,43,2013-06-06 00:00:00,"68, Rue Jouvence",Dijon,None,France,21000,8.91
26,389,39,2013-09-07 00:00:00,"4, Rue Milton",Paris,None,France,75009,8.91

#**19) BETWEEN and LIKE**

* `invoices` jadvalidan `Total` summasi 5 dan 15 gacha bo‘lgan qatorlarni tanlang.
* `customers` jadvalidan ismi `A` harfi bilan boshlanadigan foydalanuvchilarni tanlang.

In [92]:
# 19.1 BETWEEN
pd.read_sql_query("SELECT * FROM invoices WHERE Total BETWEEN 5 AND 15 LIMIT 15", db)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
1,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
2,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
3,10,46,2009-02-03 00:00:00,3 Chatham Street,Dublin,Dublin,Ireland,None,5.94
4,11,52,2009-02-06 00:00:00,202 Hoxton Street,London,None,United Kingdom,N1 5LH,8.91
5,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
6,17,25,2009-03-06 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,5.94
7,18,31,2009-03-09 00:00:00,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,8.91
8,19,40,2009-03-14 00:00:00,"8, Rue Hanovre",Paris,None,France,75002,13.86
9,24,4,2009-04-06 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,5.94
10,25,10,2009-04-09 00:00:00,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,8.91
11,26,19,2009-04-14 00:00:00,1 Infinite Loop,Cupertino,CA,USA,95014,13.86
12,31,42,2009-05-07 00:00:00,"9, Place Louis Barthou",Bordeaux,None,France,33000,5.94
13,32,48,2009-05-10 00:00:00,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,8.91
14,33,57,2009-05-15 00:00:00,"Calle Lira, 198",Santiago,None,Chile,None,13.86

In [100]:
# 19.2 LIKE
pd.read_sql_query("SELECT * FROM customers WHERE FirstName LIKE 'A%'", db)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
1,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
2,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4

#**20) DataFrame to SQL**
* Quyidagi maʼlumotlardan dataframe yarating.
  ```
  sales_data = {
    "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
    "product_name": [
        "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
        "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
        "Speaker", "Game Console", "TV", "Router", "Power Bank",
        "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
    ],
    "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
    "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
              150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
    "sale_date": [
        "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
        "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
        "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
        "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
    ]
}
```
*Yuqoridagi maʼlumotlar asosida yaratgan dataframeʼingizdan SQL jadvali tuzing va uni `sales` deb nomlang.

In [102]:
#javobni shu yerda yozing.
sales_data = {
  "sale_id": list(range(1, 21)),  # 1 dan 20 gacha boʻlgan unikal IDʼlar
  "product_name": [
      "Laptop", "Smartphone", "Tablet", "Headphones", "Smartwatch",
      "Monitor", "Keyboard", "Mouse", "Printer", "Camera",
      "Speaker", "Game Console", "TV", "Router", "Power Bank",
      "Hard Drive", "USB Flash", "Graphics Card", "Microphone", "VR Headset"
  ],
  "quantity": [2, 5, 3, 10, 4, 6, 8, 12, 3, 5, 7, 9, 4, 2, 11, 6, 15, 1, 3, 2],
  "price": [1200, 800, 450, 200, 300, 500, 100, 50, 250, 700,
            150, 400, 1000, 90, 60, 110, 30, 1500, 80, 600],
  "sale_date": [
      "2025-03-01", "2025-03-02", "2025-03-03", "2025-03-04", "2025-03-05",
      "2025-03-06", "2025-03-07", "2025-03-08", "2025-03-09", "2025-03-10",
      "2025-03-11", "2025-03-12", "2025-03-13", "2025-03-14", "2025-03-15",
      "2025-03-16", "2025-03-17", "2025-03-18", "2025-03-19", "2025-03-20"
  ]
}

df_sd = pd.DataFrame(sales_data)
df_sd

    sale_id   product_name  quantity  price   sale_date
0         1         Laptop         2   1200  2025-03-01
1         2     Smartphone         5    800  2025-03-02
2         3         Tablet         3    450  2025-03-03
3         4     Headphones        10    200  2025-03-04
4         5     Smartwatch         4    300  2025-03-05
5         6        Monitor         6    500  2025-03-06
6         7       Keyboard         8    100  2025-03-07
7         8          Mouse        12     50  2025-03-08
8         9        Printer         3    250  2025-03-09
9        10         Camera         5    700  2025-03-10
10       11        Speaker         7    150  2025-03-11
11       12   Game Console         9    400  2025-03-12
12       13             TV         4   1000  2025-03-13
13       14         Router         2     90  2025-03-14
14       15     Power Bank        11     60  2025-03-15
15       16     Hard Drive         6    110  2025-03-16
16       17      USB Flash        15     30  2025-03-17
17       18  Graphics Card         1   1500  2025-03-18
18       19     Microphone         3     80  2025-03-19
19       20     VR Headset         2    600  2025-03-20

In [103]:
df_sd.to_sql('sales', db, index=False)

20